sonar.projectKey=MithunKarthick_quiz-app_demo
sonar.organization=mithunkarthick
sonar.projectName=Quiz App Demo
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/tests/**
