name: CI Pipeline — Build & Scan

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'k8s/**'          # CRITICAL: ignore k8s folder changes to break loop
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # SonarCloud needs full history
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
        continue-on-error: true

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV  

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quiz-app:$TAG .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quiz-app:$TAG

      - name: Update deployment.yaml
        run: |
         sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/quiz-app:$TAG|g" k8s/deployment.yaml

      - name: Commit & push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }} 
        run: |
         git config user.name "github-actions"
         git config user.email "actions@github.com"
         # Replace origin URL with PAT authentication
         git remote set-url origin https://$GH_PAT@github.com/${{ github.repository }}.git
         git add k8s/deployment.yaml
         git diff --staged --quiet || git commit -m "ci: update image to $TAG [skip ci]"
         git push

        
