name: CI Pipeline — Build & Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t quiz-app:${{ github.sha }} .

      - name: Tag image
        run: docker tag quiz-app:${{ github.sha }} quiz-app:latest

      - name: Save image info
        run: |
          echo "Image built: quiz-app:${{ github.sha }}"
          docker images quiz-app
